# Generated by Django 3.2.12 on 2022-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='caulculate_command_totals',
        ),
        migrations.AddField(
            model_name='pupil',
            name='calculate_command_totals',
            field=models.BooleanField(default=False, verbose_name='calculate command totals'),
        ),
    ]
