# Generated by Django 3.2.12 on 2022-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221125_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='type_of_view',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('picto', 'Picto'), ('video', 'Video')], default='text', max_length=48),
        ),
    ]
